"""Converts the 4 tank pose sprites (32x32, Sprite Editor JSON) into
MSX hardware sprite pattern data: each 32x32 pose = 2x2 arrangement of
16x16 sprites (top-left/top-right/bottom-left/bottom-right), each
16x16 sprite = 4 8x8 sub-patterns in [top-left][bottom-left]
[top-right][bottom-right] byte order (32 bytes) - the same convention
already used for the player ship (see SHIP_MID_PATTERN in
src/CYBER SHMUP.asm).

Poses:
  TankF    - driving straight, on flat ground
  TankUp   - up+fire (45-degree shot), on flat ground
  TankFGap - driving straight, tilted to follow a slope transition cell
  TankUGap - up+fire, tilted to follow a slope transition cell
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SPRITE_DIR = os.path.join(HERE, "sprites")

POSES = ["TankF", "TankUp", "TankFGap", "TankUGap"]


def load_bits(name):
    return json.load(open(os.path.join(SPRITE_DIR, f"{name}.json")))["bits"]


def sub8(bits, row0, col0):
    return [row[col0:col0 + 8] for row in bits[row0:row0 + 8]]


def to_bytes(tile8x8):
    out = []
    for row in tile8x8:
        b = 0
        for i, v in enumerate(row):
            if v:
                b |= (0x80 >> i)
        out.append(b)
    return out


def block16_bytes(bits, row0, col0):
    """One 16x16 sprite's 32 bytes: TL8,BL8,TR8,BR8 sub-quadrants."""
    tl = to_bytes(sub8(bits, row0, col0))
    bl = to_bytes(sub8(bits, row0 + 8, col0))
    tr = to_bytes(sub8(bits, row0, col0 + 8))
    br = to_bytes(sub8(bits, row0 + 8, col0 + 8))
    return tl + bl + tr + br


def pose_quadrants(name):
    """Returns [TL(32B), TR(32B), BL(32B), BR(32B)] for one 32x32 pose."""
    bits = load_bits(name)
    tl = block16_bytes(bits, 0, 0)
    tr = block16_bytes(bits, 0, 16)
    bl = block16_bytes(bits, 16, 0)
    br = block16_bytes(bits, 16, 16)
    return [tl, tr, bl, br]


ALL_QUADRANTS = {name: pose_quadrants(name) for name in POSES}


def db_bytes(byte_list, per_line=16):
    lines = []
    for i in range(0, len(byte_list), per_line):
        chunk = byte_list[i:i + per_line]
        lines.append("    DB " + ",".join(f"{b}" for b in chunk))
    return "\n".join(lines)


def emit_asm_tables():
    """Each pose gets 4 consecutive pattern-group numbers (TL,TR,BL,BR),
    16 apart per pose so pose groups never overlap (4 quadrants x 4
    slots-of-8-bytes each = 16 slots per pose)."""
    out = ["; ===== Tank sprite patterns: generated by tank_gen.py, do not hand-edit ====="]
    for pi, name in enumerate(POSES):
        base = pi * 16
        out.append(f"PAT_{name.upper()} EQU {base}")
        quads = ALL_QUADRANTS[name]
        labels = ["TL", "TR", "BL", "BR"]
        for qi, q in enumerate(quads):
            out.append(f"TANK_{name.upper()}_{labels[qi]}:")
            out.append(db_bytes(q))
    return "\n".join(out)


if __name__ == "__main__":
    for name in POSES:
        print(name, "converted, 4x32 bytes")
    tables_path = os.path.join(HERE, "tank_tables.inc.asm")
    with open(tables_path, "w") as f:
        f.write(emit_asm_tables())
    print("wrote", tables_path)
