"""SCREEN3(Multicolor)画像表示テスト用ROM(2026-09-12、"添付ファイルは
スクリーン3用の画像データ この画像を表示してみてくれ 表示テスト用の
ROMを作る ベースはタイトル表示までを流用 それ以外は空でいい")。

添付BSAVE形式ダンプ(01.SC3、start=0000h/end=203Fh、payload8256byte)の
実バイトを調査した結果、この特定ファイルの内部レイアウトは"標準的な
BASIC SCREEN3デフォルト"(パターンジェネレータ0000h/ネームテーブル
1800h)とは異なり、詰めて保存されていると判明した:

  0000h-07FFh (2048byte): パターンジェネレータ(実絵柄データ、非ゼロ・
                           高エントロピー)
  0800h-0AFFh (768byte) : ネームテーブル(実測: 0,1,2,...,31を32byte
                           周期で4回繰り返し→32,33,...,63を4回→...という
                           規則的なランプ - "name = 32*(row_of_name//4)
                           +col"という機械的な割り当て、TMS9918
                           マルチカラーモードの仕様(1パターンあたり
                           8byteの割り当てのうち、row_of_name%4で
                           選ぶペア×Y&4の上下半分=8通りをフルに使う
                           ため、同じ4行グループ内は同じname値で
                           構わない)と正確に整合)
  0B00h以降              : 同じランプの続き(絵とは無関係な後続データ、
                           未使用)

実際にPGT(0000h-07FFh)+NAME(0800h-0AFFh)をこの解釈でレンダリングし
Pillowで視覚確認済み(人物キャラクターの絵が正しく表示される)。

表示時はVDPレジスタ設定(パターンジェネレータ/ネームテーブル/
スプライト属性テーブルのアドレス)はBIOS標準デフォルト(INIMLT任せ、
PGT=0000h/NAME=1800h/SPRAT=1B00h)のまま使う - ソースファイル内での
詰め方(NAMEが0800hにある)とは無関係に、実際にVRAMへ書き込む先
アドレスは標準デフォルトの1800hを使う(この生成スクリプトが抽出時に
0800hから読み、書き込みAsm側は1800hへLDIRVMする)。
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SC3_PATH = os.path.join(HERE, "assets", "TestImage.SC3")

PGT_LEN = 0x0800   # 2048 bytes - pattern generator (standard SCREEN1/3 size)
NAME_LEN = 0x0300  # 768 bytes - name table (32x24)
NAME_SRC_OFFSET = 0x0800  # where THIS file's payload actually packs the name table


def load_payload(path=SC3_PATH):
    with open(path, "rb") as f:
        data = f.read()
    assert data[0] == 0xFE, f"not a BSAVE-format file (marker byte was {data[0]:02X}h)"
    start = data[1] | (data[2] << 8)
    assert start == 0x0000, f"expected VRAM start 0000h, got {start:04X}h"
    payload = data[7:]
    assert len(payload) >= NAME_SRC_OFFSET + NAME_LEN, \
        f"payload too short ({len(payload)} bytes) to contain the name table at {NAME_SRC_OFFSET:04X}h"
    return payload


def pattern_generator():
    return load_payload()[0:PGT_LEN]


def name_table():
    return load_payload()[NAME_SRC_OFFSET:NAME_SRC_OFFSET + NAME_LEN]


def db_bytes(byte_list, per_line=16):
    lines = []
    for i in range(0, len(byte_list), per_line):
        chunk = byte_list[i:i + per_line]
        lines.append("    DB " + ",".join(str(b) for b in chunk))
    return "\n".join(lines)


def emit_asm_tables():
    pgt = pattern_generator()
    name = name_table()
    out = ["; ===== SCREEN3 test image (01.SC3), generated by screen3_gen.py - "
           "do not hand-edit ====="]
    out.append("SC3_PGT:")
    out.append(db_bytes(list(pgt)))
    out.append("SC3_PGT_LEN EQU $ - SC3_PGT")
    out.append("SC3_NAME:")
    out.append(db_bytes(list(name)))
    out.append("SC3_NAME_LEN EQU $ - SC3_NAME")
    return "\n".join(out)


if __name__ == "__main__":
    pgt = pattern_generator()
    name = name_table()
    print(f"pattern generator: {len(pgt)} bytes")
    print(f"name table: {len(name)} bytes")
