"""SCREEN3(Multicolor)画像表示テスト用ROM(2026-09-12、"では取り敢えず
組み込みはせずテストをする...この画像を表示してみてくれ 表示テスト用の
ROMを作る ベースはタイトル表示までを流用 それ以外は空でいい"に対する
実機フィードバック"おｋ意図通り表示できた 次はこの6枚を連続で表示
3回繰り返して"で6枚のスライドショーへ拡張)。

添付BSAVE形式ダンプ(01.SC3〜06.SC3、いずれもstart=0000h/end=203Fh/
payload8256byte、全6枚とも同一レイアウトと実測確認済み)の実バイトを
調査した結果、この特定ファイル群の内部レイアウトは"標準的なBASIC
SCREEN3デフォルト"(パターンジェネレータ0000h/ネームテーブル1800h)とは
異なり、詰めて保存されていると判明した:

  0000h-07FFh (2048byte): パターンジェネレータ(実絵柄データ、非ゼロ・
                           高エントロピー)
  0800h-0AFFh (768byte) : ネームテーブル(実測: 0,1,2,...,31を32byte
                           周期で4回繰り返し→32,33,...,63を4回→...という
                           規則的なランプ - "name = 32*(row_of_name//4)
                           +col"という機械的な割り当て、TMS9918
                           マルチカラーモードの仕様(1パターンあたり
                           8byteの割り当てのうち、row_of_name%4で
                           選ぶペア×Y&4の上下半分=8通りをフルに使う
                           ため、同じ4行グループ内は同じname値で
                           構わない)と正確に整合)
  0B00h以降              : 同じランプの続き(絵とは無関係な後続データ、
                           未使用)

表示時はVDPレジスタ設定(パターンジェネレータ/ネームテーブル/
スプライト属性テーブルのアドレス)はBIOS標準デフォルト(INIT32任せ、
PGT=0000h/NAME=1800h/SPRAT=1B00h)のまま使う - ソースファイル内での
詰め方(NAMEが0800hにある)とは無関係に、実際にVRAMへ書き込む先
アドレスは標準デフォルトの1800hを使う(この生成スクリプトが抽出時に
0800hから読み、書き込みAsm側は1800hへLDIRVMする)。
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ASSETS = os.path.join(HERE, "assets")

PGT_LEN = 0x0800   # 2048 bytes - pattern generator (standard SCREEN1/3 size)
NAME_LEN = 0x0300  # 768 bytes - name table (32x24)
NAME_SRC_OFFSET = 0x0800  # where these files actually pack the name table

IMAGE_COUNT = 6


def load_payload(index):
    """index: 1-6."""
    path = os.path.join(ASSETS, f"Image{index:02d}.SC3")
    with open(path, "rb") as f:
        data = f.read()
    assert data[0] == 0xFE, f"{path}: not a BSAVE-format file (marker byte was {data[0]:02X}h)"
    start = data[1] | (data[2] << 8)
    assert start == 0x0000, f"{path}: expected VRAM start 0000h, got {start:04X}h"
    payload = data[7:]
    assert len(payload) >= NAME_SRC_OFFSET + NAME_LEN, \
        f"{path}: payload too short ({len(payload)} bytes) to contain the name table at {NAME_SRC_OFFSET:04X}h"
    return payload


def pattern_generator(index):
    return load_payload(index)[0:PGT_LEN]


def name_table(index):
    return load_payload(index)[NAME_SRC_OFFSET:NAME_SRC_OFFSET + NAME_LEN]


def db_bytes(byte_list, per_line=16):
    lines = []
    for i in range(0, len(byte_list), per_line):
        chunk = byte_list[i:i + per_line]
        lines.append("    DB " + ",".join(str(b) for b in chunk))
    return "\n".join(lines)


def emit_asm_tables():
    out = ["; ===== SCREEN3 slideshow images (Image01-06.SC3), generated by "
           "screen3_gen.py - do not hand-edit ====="]
    for i in range(1, IMAGE_COUNT + 1):
        pgt = pattern_generator(i)
        name = name_table(i)
        out.append(f"SC3_IMG{i}_PGT:")
        out.append(db_bytes(list(pgt)))
        out.append(f"SC3_IMG{i}_PGT_LEN EQU $ - SC3_IMG{i}_PGT")
        out.append(f"SC3_IMG{i}_NAME:")
        out.append(db_bytes(list(name)))
        out.append(f"SC3_IMG{i}_NAME_LEN EQU $ - SC3_IMG{i}_NAME")
    return "\n".join(out)


if __name__ == "__main__":
    for i in range(1, IMAGE_COUNT + 1):
        pgt = pattern_generator(i)
        name = name_table(i)
        print(f"Image{i:02d}.SC3: pattern generator {len(pgt)} bytes, name table {len(name)} bytes")
