"""SCREEN3(Multicolor)画像表示テスト用ROM(2026-09-12、"では取り敢えず
組み込みはせずテストをする...この画像を表示してみてくれ"に始まり、
6枚スライドショー化・3フレームループ化を経て、"では差分圧縮では"→
"やってくれ"で差分(XOR)圧縮方式へ再設計)。

添付BSAVE形式ダンプ(01.SC3〜06.SC3、いずれもstart=0000h/end=203Fh/
payload8256byte、全6枚とも同一レイアウトと実測確認済み)の実バイトを
調査した結果:

  0000h-07FFh (2048byte): パターンジェネレータ(実絵柄データ)
  0800h-0AFFh (768byte) : ネームテーブル(name=32*(row_of_name//4)+col
                           という機械的なランプ - TMS9918マルチカラー
                           モードの仕様と正確に整合)
  0B00h以降              : 同じランプの続き(絵とは無関係、未使用)

**差分圧縮の設計**: ネームテーブルは6枚とも完全にバイト一致(実測
確認済み)なので1回だけ保持すれば良い。パターンジェネレータは
フレーム間で16-22%だけ異なる(実測)ため、1枚目は通常のRLE圧縮で
フル保持し、2〜6枚目は「直前のフレームとのXOR差分」をRLE圧縮して
保持する(差分の大半は0=無変化のため通常のRLEより大幅に縮む -
実測16896byte独立圧縮12287byte→差分圧縮5637byte)。実行時はRAM上に
2048byteの「現在のPGTの実体」を保持するシャドウバッファを持ち、
1枚目はそこへ展開してからVRAMへ一括LDIRVM、2枚目以降は差分をその
シャドウバッファへXOR適用してから同じくLDIRVMでVRAMへ反映する
(combined_test.asm側のSHOW_IMG1-6参照)。
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ASSETS = os.path.join(HERE, "assets")

PGT_LEN = 0x0800   # 2048 bytes - pattern generator (standard SCREEN1/3 size)
NAME_LEN = 0x0300  # 768 bytes - name table (32x24)
NAME_SRC_OFFSET = 0x0800  # where these files actually pack the name table

IMAGE_COUNT = 6

sys.path.insert(0, os.path.join(HERE, "..", "title_screen"))
import title_bg_gen  # noqa: E402  (汎用: rle_encode/rle_decode)


def load_payload(index):
    """index: 1-6."""
    path = os.path.join(ASSETS, f"Image{index:02d}.SC3")
    with open(path, "rb") as f:
        data = f.read()
    assert data[0] == 0xFE, f"{path}: not a BSAVE-format file (marker byte was {data[0]:02X}h)"
    start = data[1] | (data[2] << 8)
    assert start == 0x0000, f"{path}: expected VRAM start 0000h, got {start:04X}h"
    payload = data[7:]
    assert len(payload) >= NAME_SRC_OFFSET + NAME_LEN, \
        f"{path}: payload too short ({len(payload)} bytes) to contain the name table at {NAME_SRC_OFFSET:04X}h"
    return payload


def pattern_generator(index):
    return load_payload(index)[0:PGT_LEN]


def name_table(index):
    return load_payload(index)[NAME_SRC_OFFSET:NAME_SRC_OFFSET + NAME_LEN]


def shared_name_table():
    """全6枚で完全一致(実測確認済み)なので1枚目のものを代表として使う。"""
    base = name_table(1)
    for i in range(2, IMAGE_COUNT + 1):
        assert name_table(i) == base, f"Image{i:02d}.SC3's name table differs from Image01 - shared-table assumption broken"
    return base


def xor_bytes(a, b):
    return bytes(x ^ y for x, y in zip(a, b))


def db_bytes(byte_list, per_line=16):
    lines = []
    for i in range(0, len(byte_list), per_line):
        chunk = byte_list[i:i + per_line]
        lines.append("    DB " + ",".join(str(b) for b in chunk))
    return "\n".join(lines)


def emit_asm_tables():
    out = ["; ===== SCREEN3 slideshow images (Image01-06.SC3), differential (XOR) "
           "RLE-compressed (tools/title_screen/title_bg_gen.py's codec) - generated by "
           "screen3_gen.py, do not hand-edit ====="]

    # shared NAME table (raw - RLE doesn't help this ramp, and it's only stored once)
    name = shared_name_table()
    out.append("SC3_SHARED_NAME:")
    out.append(db_bytes(list(name)))
    out.append(f"SC3_SHARED_NAME_LEN EQU {len(name)}")

    # image1: full RLE-compressed PGT (base frame)
    pgts = [pattern_generator(i) for i in range(1, IMAGE_COUNT + 1)]
    base_c, base_segs = title_bg_gen.rle_encode(pgts[0])
    assert title_bg_gen.rle_decode(base_c, base_segs) == pgts[0], "image1: base PGT RLE round-trip mismatch"
    out.append("SC3_IMG1_PGT_RLE:")
    out.append(db_bytes(list(base_c)))
    out.append(f"SC3_IMG1_PGT_SEGMENTS EQU {base_segs}")

    # images 2-6: XOR-diff against the previous frame, RLE-compressed
    for i in range(2, IMAGE_COUNT + 1):
        diff = xor_bytes(pgts[i - 2], pgts[i - 1])
        diff_c, diff_segs = title_bg_gen.rle_encode(diff)
        assert title_bg_gen.rle_decode(diff_c, diff_segs) == diff, f"image{i}: XOR-diff RLE round-trip mismatch"
        out.append(f"SC3_IMG{i}_PGT_XORDIFF:")
        out.append(db_bytes(list(diff_c)))
        out.append(f"SC3_IMG{i}_PGT_SEGMENTS EQU {diff_segs}")

    return "\n".join(out)


if __name__ == "__main__":
    pgts = [pattern_generator(i) for i in range(1, IMAGE_COUNT + 1)]
    base_c, base_segs = title_bg_gen.rle_encode(pgts[0])
    total = len(base_c)
    print(f"img1 (base): {len(pgts[0])} -> {len(base_c)}B ({base_segs} seg)")
    for i in range(2, IMAGE_COUNT + 1):
        diff = xor_bytes(pgts[i - 2], pgts[i - 1])
        diff_c, diff_segs = title_bg_gen.rle_encode(diff)
        print(f"img{i} (diff vs img{i-1}): -> {len(diff_c)}B ({diff_segs} seg)")
        total += len(diff_c)
    name = shared_name_table()
    total += len(name)
    print(f"shared NAME table: {len(name)}B")
    print(f"TOTAL: {total} bytes")
