"""確認音(Round69の"Rising alert chirp"->"Descending buzzer"、53行)を
割り込み(H.TIMI)駆動で再生するための、vblank tick単位のデータテーブルを
生成する(2026-09-12、実機フィードバック"音は出てるが...表示すらできて
ねえんだよ"→表示修正後、続けて"表示は出来た だが音2回鳴らして1コマ
じゃねえんだよ 音は割り込みで鳴らしてんだろうが 鳴らしながらアニメ
するんだよ")。

従来のPLAY_CONFIRM_BEEP/PLAY_CONFIRM_BEEP_NO_BORDERは「1行=(ON半区間+
OFF半区間)をそれぞれZ80クロック直接カウントのbusy-waitで待つ」という
自己完結した同期呼び出し(1回の呼び出しで約0.69秒×2周=約1.4秒かかる)
だったため、RUN_SCREEN3_SLIDESHOWからは画像の切り替わりごとに毎回
"CALL"して待たせる形になっていた(結果として「1コマに対し確認音が
2回鳴る」形になり、かつ画像切り替えが確認音の再生時間に引きずられて
不自然に遅くなっていた)。

このモジュールはCONFIRM_STEPS(title_test.asm内にDBリテラルとして
既存)と全く同じ周期/音量シーケンスを、Stage2のBGM_TICKと同じ
「H.TIMIで1tick=1vblankごとに1行ずつ自動で進む・末尾まで行ったら
先頭へループする」設計に変換する。各行の元の「半区間ウェイト値
(Z80クロック直接カウント、26T-state/iteration)」を実時間へ変換し
(duration_seconds = 2*wait*26/3579545、ON+OFF両半区間の合計)、
60Hz vblank tick数に丸める(最小1tick)。デューティ50%の細かい
明滅は1tick未満の解像度になるため今回は再現せず、各行を一定音量で
そのtick数だけ鳴らす(BGM_TICK自身のノート単位の音量表現と同じ
考え方 - 割り込み駆動である以上vblank精度が自然な上限)。
"""

HALF = {"RISE": (108, 2), "HOLD": (34, 16), "FADE": (57, 3), "BUZZ": (217, 3)}
CLOCK_HZ = 3579545
TICK_HZ = 60


def sim_sweep(a, b, n):
    return [round(a + (b - a) * i / (n - 1)) for i in range(n)]


def _rows():
    rise = sim_sweep(520, 180, 10)
    buzz = sim_sweep(140, 440, 14)
    rows = []
    for p in rise:
        rows.append((p, 14, "RISE"))
    rows.append((180, 14, "HOLD"))
    for v in range(14, 0, -1):
        rows.append((180, v, "FADE"))
    for p in buzz:
        rows.append((p, 14, "BUZZ"))
    for v in range(14, 0, -1):
        rows.append((440, v, "FADE"))
    assert len(rows) == 53
    return rows


def tick_rows():
    """[(period_lo, period_hi, volume, duration_ticks), ...] - 53要素。"""
    out = []
    for period, volume, tag in _rows():
        wait = HALF[tag][0] | (HALF[tag][1] << 8)
        duration_tstates = 2 * wait * 26  # ON半区間+OFF半区間(元の設計通り同じ長さ)
        seconds = duration_tstates / CLOCK_HZ
        ticks = max(1, round(seconds * TICK_HZ))
        assert ticks < 256, f"tick count {ticks} overflows the 1-byte duration field"
        out.append((period & 0xFF, (period >> 8) & 0xFF, volume, ticks))
    return out


def db_bytes(byte_list, per_line=16):
    lines = []
    for i in range(0, len(byte_list), per_line):
        chunk = byte_list[i:i + per_line]
        lines.append("    DB " + ",".join(str(b) for b in chunk))
    return "\n".join(lines)


def emit_asm_table():
    rows = tick_rows()
    flat = []
    for lo, hi, vol, ticks in rows:
        flat.extend([lo, hi, vol, ticks])
    out = ["; ===== SCREEN3 slideshow confirm-chirp, H.TIMI-driven tick table "
           "(period_lo,period_hi,volume,duration_ticks x53 rows) - generated by "
           "confirm_beep_gen.py from the same chirp/buzzer sweep as CONFIRM_STEPS, "
           "do not hand-edit ====="]
    out.append("SC3_CONFIRM_TICKS:")
    out.append(db_bytes(flat))
    out.append(f"SC3_CONFIRM_TICK_ROW_COUNT EQU {len(rows)}")
    return "\n".join(out)


if __name__ == "__main__":
    rows = tick_rows()
    total_ticks = sum(r[3] for r in rows)
    print(f"{len(rows)} rows, {total_ticks} ticks total (~{total_ticks/TICK_HZ:.2f}s per loop pass)")
    for r in rows:
        print(r)
