"""SCREEN3(Multicolor)スライドショーの締めくくり3枚(2026-09-12、
"ではさっきの6枚の後に一枚目を0.5秒 これを4ループ その後に2枚目を1秒
3枚目を3秒表示"→実機フィードバック"画像データは間違えた 添付の3枚"で
実際のBSAVE形式SC3ダンプ[08.SC3/09.SC3/11.SC3、tools/screen3_test/
screen3_gen.pyのImage01-06.SC3と全く同じレイアウト]へ差し替え済み)。

当初は256x192のPNG3枚(モンスターの顔をズームインしていく演出用に
ユーザーが用意した参考画像)を自前のPNG→Multicolorエンコーダで量子化
していたが、ユーザーから「画像データは間違えた」との指摘を受け、
Image01-06.SC3と同じ本物のBSAVE形式SC3ダンプへ全面差し替えた
(エンコーダ自体はもう不要 - screen3_gen.pyのload_payload/pattern_
generatorと全く同じ読み込みロジックをそのまま再利用する)。

ネームテーブルはこの3枚も実測でImage01-06.SC3と完全にバイト一致
(screen3_gen.shared_name_table()と同一)と確認済みのため、この3枚
専用の別ネームテーブルは持たず、SC3_SHARED_NAMEをそのまま再利用する
(生成するのはPGT[2048byte]のXOR差分のみ)。

差分[XOR]圧縮の連鎖はtools/screen3_test/screen3_gen.pyと同じ設計を
踏襲: エピローグ1枚目は本編6枚目(Image06.SC3)からのXOR差分、2枚目は
1枚目からの差分、3枚目は2枚目からの差分(呼び出し順序が固定されている
前提、title_test.asmのRUN_SCREEN3_SLIDESHOWが必ずこの順で呼ぶ)。
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.join(HERE, "..", "..")

sys.path.insert(0, HERE)
import title_bg_gen  # noqa: E402  (rle_encode/rle_decode)

sys.path.insert(0, os.path.join(REPO, "tools", "screen3_test"))
import screen3_gen  # noqa: E402  (load_payload/pattern_generator/shared_name_table)

ASSETS = screen3_gen.ASSETS  # 添付の08/09/11.SC3もtools/screen3_test/assets/へ配置済み
EPILOGUE_COUNT = 3


def load_epilogue_payload(index):
    """index: 1-3。screen3_gen.load_payload()と全く同じBSAVE形式読み込み
    (Image01-06.SC3と全く同じレイアウト、実測確認済み)。"""
    path = os.path.join(ASSETS, f"Epilogue{index}.SC3")
    with open(path, "rb") as f:
        data = f.read()
    assert data[0] == 0xFE, f"{path}: not a BSAVE-format file (marker byte was {data[0]:02X}h)"
    start = data[1] | (data[2] << 8)
    assert start == 0x0000, f"{path}: expected VRAM start 0000h, got {start:04X}h"
    payload = data[7:]
    assert len(payload) >= screen3_gen.NAME_SRC_OFFSET + screen3_gen.NAME_LEN, \
        f"{path}: payload too short ({len(payload)} bytes)"
    return payload


def epilogue_pattern_generator(index):
    return load_epilogue_payload(index)[0:screen3_gen.PGT_LEN]


def epilogue_pgt(index):
    """screen3_epilogue_gen旧APIとの互換用エイリアス。"""
    return epilogue_pattern_generator(index)


def _check_shared_name_table():
    """3枚ともImage01-06.SC3と同一の共有ランプ(SC3_SHARED_NAME)である
    ことを実測確認する(実機フィードバックで確認済みだが、将来別の
    画像に差し替えられた場合に静かに壊れないようビルド時にも検証)。"""
    base = screen3_gen.shared_name_table()
    for i in range(1, EPILOGUE_COUNT + 1):
        name = load_epilogue_payload(i)[screen3_gen.NAME_SRC_OFFSET:
                                         screen3_gen.NAME_SRC_OFFSET + screen3_gen.NAME_LEN]
        assert name == base, \
            f"Epilogue{i}.SC3's name table differs from the main 6 images' shared ramp"


def xor_bytes(a, b):
    return bytes(x ^ y for x, y in zip(a, b))


def db_bytes(byte_list, per_line=16):
    lines = []
    for i in range(0, len(byte_list), per_line):
        chunk = byte_list[i:i + per_line]
        lines.append("    DB " + ",".join(str(b) for b in chunk))
    return "\n".join(lines)


def emit_asm_tables():
    _check_shared_name_table()
    out = ["; ===== SCREEN3 slideshow epilogue images (Epilogue1-3.SC3), "
           "differential (XOR) RLE-compressed against the main 6-image "
           "loop's final frame (Image06.SC3) - generated by "
           "screen3_epilogue_gen.py, do not hand-edit ====="]

    prev = screen3_gen.pattern_generator(6)  # main loop's last frame (SHADOW_PGT state at epilogue start)
    for i in range(1, EPILOGUE_COUNT + 1):
        cur = epilogue_pattern_generator(i)
        diff = xor_bytes(prev, cur)
        diff_c, diff_segs = title_bg_gen.rle_encode(diff)
        assert title_bg_gen.rle_decode(diff_c, diff_segs) == diff, \
            f"epilogue{i}: XOR-diff RLE round-trip mismatch"
        out.append(f"SC3_EPI{i}_PGT_XORDIFF:")
        out.append(db_bytes(list(diff_c)))
        out.append(f"SC3_EPI{i}_PGT_SEGMENTS EQU {diff_segs}")
        prev = cur

    return "\n".join(out)


if __name__ == "__main__":
    _check_shared_name_table()
    prev = screen3_gen.pattern_generator(6)
    total = 0
    for i in range(1, EPILOGUE_COUNT + 1):
        cur = epilogue_pattern_generator(i)
        diff = xor_bytes(prev, cur)
        diff_c, diff_segs = title_bg_gen.rle_encode(diff)
        print(f"epilogue{i} (diff vs {'Image06.SC3' if i == 1 else f'epilogue{i-1}'}): "
              f"-> {len(diff_c)}B ({diff_segs} seg)")
        total += len(diff_c)
        prev = cur
    print(f"TOTAL: {total} bytes")
