"""Extracts real, already-shipped boss art for the new title-screen bank
test (round39, "バンクテストをしたいので...PUSH STARTと表示しStage1と
Stage2のボスを適当に表示して") - not new art, just reusing what already
exists so the "banking works" test has something recognizable to show:

- Stage1's boss (src/CYBER SHMUP.asm's own BOSS_PATTERNS/BOSS_MAP - a
  5x16 grid of 8x8 BG tiles, drawn the exact same way that file's own
  BOSS_SPAWN loads it) - pulled out of a real assemble of that file
  rather than hand-copied, so it can never drift from the shipped art.
- Stage2's boss (tools/stage2_combined/sasapi_gen.py's own SASAPI_QUADS -
  16 quadrants of 32 bytes each, the same hw-sprite-pattern format its
  own emit_asm_tables() already produces) - imported directly, not
  regenerated by hand.
"""
import importlib.util
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.join(HERE, "..", "..")
sys.path.insert(0, os.path.join(REPO, "tools"))
sys.path.insert(0, os.path.join(REPO, "tools", "stage2_combined"))

from mini_z80asm import Assembler  # noqa: E402
import sasapi_gen  # noqa: E402


def _assemble_stage1():
    src_path = os.path.join(REPO, "src", "CYBER SHMUP.asm")
    text = open(src_path, encoding="utf-8").read()
    a = Assembler(text)
    out = a.assemble()
    return out, a.symtab


def stage1_boss_patterns():
    """512 bytes: BOSS_PATTERNS, the 64 BG pattern codes (192-255) Stage1's
    own BOSS_SPAWN loads at boss-spawn time."""
    out, sym = _assemble_stage1()
    base = sym["BOSS_PATTERNS"]
    return [out[base + i] for i in range(512)]


def stage1_boss_map():
    """80 bytes: BOSS_MAP, a 5-wide x16-tall grid of absolute pattern
    codes (matching stage1_boss_patterns()'s own 192-255 range, plus
    code48 - Stage1's own reused "blank" tile elsewhere in its layout)."""
    out, sym = _assemble_stage1()
    base = sym["BOSS_MAP"]
    return [out[base + i] for i in range(80)]


def stage1_blank48_pattern():
    """8 bytes: Stage1's own code48 art (whatever BOSS_MAP's blank cells
    actually reference) - pulled the same way as the boss patterns above
    so this title bank's own code48 renders identically instead of
    guessing "all zero" and risking a visibly different blank tile."""
    out, sym = _assemble_stage1()
    # code48's pattern-generator bytes live at PATTERNS' own load target
    # (0000h + 48*8), not a named symbol - PATTERNS is LDIRVM'd flat into
    # VRAM at INIT, so the byte at ROM label PATTERNS+48*8 is code48's art.
    base = sym["PATTERNS"] + 48 * 8
    return [out[base + i] for i in range(8)]


def stage2_boss_quads():
    """16 quadrants x 32 bytes (512 bytes total) = Sasapi's normal-facing
    hw sprite pattern data, TL/BL/TR/BR-per-16x16-quadrant, row-major
    (matches BOSS_QUAD_OFFSETS' own walk order in combined_test.asm)."""
    bits = sasapi_gen.load_bits("Sasapi")
    quads = sasapi_gen.quadrants_from_bits(bits)
    flat = []
    for q in quads:
        flat.extend(q)
    assert len(flat) == 512
    return flat


# same (Y-delta, X-delta, pattern-code-offset) triples as combined_test.
# asm's own BOSS_QUAD_OFFSETS - the universal row-major layout for any
# 4x4 grid of 16x16 quadrants reconstructing a 64x64 sprite, reused
# verbatim rather than re-derived (it's a fixed geometric fact of the
# quadrant walk order, not game-specific).
QUAD_OFFSETS = [
    (0, 0, 0), (0, 16, 4), (0, 32, 8), (0, 48, 12),
    (16, 0, 16), (16, 16, 20), (16, 32, 24), (16, 48, 28),
    (32, 0, 32), (32, 16, 36), (32, 32, 40), (32, 48, 44),
    (48, 0, 48), (48, 16, 52), (48, 32, 56), (48, 48, 60),
]


def stage2_boss_sprite_attrs(base_y, base_x, base_code, color):
    """64 bytes: 16 hw sprite attribute entries (Y,X,pattern,color), one
    per 16x16 quadrant, positioned to reconstruct the 64x64 body at
    (base_x,base_y) - computed once here (all compile-time constants,
    no runtime per-entry math needed) so title_test.asm can LDIRVM this
    straight into the sprite attribute table."""
    out = []
    for dy, dx, off in QUAD_OFFSETS:
        out.extend([(base_y + dy) & 0xFF, (base_x + dx) & 0xFF, base_code + off, color])
    return out


def emit_boss1_draw_loop(namtbl, start_row, start_col, map_label="TITLE_STAGE1_BOSS_MAP"):
    """Unrolled 16-row draw sequence (5 bytes/row, source contiguous but
    dest jumps by 32/row) - addresses computed here in Python rather
    than via in-ASM multiplication, since this project's own assembler
    (mini_z80asm.py) evaluates expressions strictly left-to-right with
    no operator precedence (see combined_test.asm's own "BASE+N*4"
    round36-14 follow-up#8 bug) - safest to just never hand it an
    expression more complex than a single literal here."""
    lines = []
    for row in range(16):
        dest = namtbl + (start_row + row) * 32 + start_col
        lines.append(f"    LD HL,{map_label}+{row * 5}")
        lines.append(f"    LD DE,{dest}")
        lines.append("    LD BC,5")
        lines.append("    CALL LDIRVM")
    return "\n".join(lines)


def db_bytes(byte_list, per_line=16):
    lines = []
    for i in range(0, len(byte_list), per_line):
        chunk = byte_list[i:i + per_line]
        lines.append("    DB " + ",".join(str(b) for b in chunk))
    return "\n".join(lines)


def emit_asm_tables():
    out = ["; ===== title screen boss art: generated by title_gen.py, do not hand-edit ====="]
    out.append("TITLE_STAGE1_BOSS_PATTERNS:")
    out.append(db_bytes(stage1_boss_patterns()))
    out.append("TITLE_STAGE1_BOSS_MAP:")
    out.append(db_bytes(stage1_boss_map(), per_line=5))
    out.append("TITLE_STAGE1_BLANK48_PATTERN:")
    out.append(db_bytes(stage1_blank48_pattern()))
    out.append("TITLE_STAGE2_BOSS_QUADS:")
    out.append(db_bytes(stage2_boss_quads()))
    out.append("TITLE_STAGE2_BOSS_SPRITE_ATTRS:")
    out.append(db_bytes(stage2_boss_sprite_attrs(base_y=40, base_x=170, base_code=0, color=15), per_line=4))
    return "\n".join(out)


if __name__ == "__main__":
    print("stage1 boss patterns:", len(stage1_boss_patterns()), "bytes")
    print("stage1 boss map:", len(stage1_boss_map()), "bytes")
    print("stage1 blank48:", len(stage1_blank48_pattern()), "bytes")
    print("stage2 boss quads:", len(stage2_boss_quads()), "bytes")
