"""タイトル画面をSCREEN2の描き下ろしアートに差し替える件(ユーザー
指示: "添付ファイルはスクリーン2用のSC2ファイル これをタイトル画面に
変更 但し簡単な圧縮をかけてくれ MSXでも使える程度のデコードが軽い物")。

tools/title_screen/assets/Title.SC2 (BSAVE形式のVRAMダンプ、開始
0000h-終了37FFhの14336バイト=パターンジェネレータ0000h-17FFh[6144B]+
ネームテーブル/スプライト属性/未使用域1800h-1FFFh[2048B]+カラー
テーブル2000h-37FFh[6144B])を、実行時デコードが数命令で済む単純な
RLE(run-length encoding)で圧縮してASMへ埋め込む。

圧縮フォーマット(PackBitsのような既存規格ではなく、Z80側のデコードを
最短にするための自前の対称な設計):
  制御バイトC:
    bit7=0: リテラル。長さ=(C&7Fh)+1(1-128)、続けてその長さ分の
            バイト列をそのままVRAMへ書く。
    bit7=1: 反復。長さ=(C&7Fh)+1(1-128)、続く1バイトをその長さ分
            繰り返してVRAMへ書く。
  終端はセグメント数(制御バイト+データの組の個数)を別途16bit定数で
  持つ方式にして、圧縮ストリーム自体に終端マーカーを持たせない
  (Z80側のループ条件を「セグメント数を1つずつ消費してゼロになったら
  終了」という単純なdown-counterにできるため)。

実データでの圧縮率実測(2026-09-06時点): パターンジェネレータ約78%
(繰り返しの多い塗り面が効く)、ネームテーブル+属性+隙間域は約40%
(大半が0埋めの未使用領域)、カラーテーブルはほぼ圧縮されない(実測
100.3%、8ピクセル単位でfg/bg配色が細かく変わる精密なドット絵のため
連続同値がほとんど無く、これは輝度データそのもののエントロピーで
アルゴリズムの欠陥ではない)。全体では約18%の削減(詳しくは
__main__の出力を参照)。
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SC2_PATH = os.path.join(HERE, "assets", "Title.SC2")

PAYLOAD_LEN = 0x3800  # 0000h-37FFh inclusive = pattern gen + name/attr/gap + color table


def load_sc2_payload(path=SC2_PATH):
    """BSAVE形式(先頭7バイト: FEh, start_lo,start_hi, end_lo,end_hi,
    exec_lo,exec_hi)のヘッダを検証し、実データ部分(VRAM 0000h起点)を
    返す。"""
    with open(path, "rb") as f:
        data = f.read()
    assert data[0] == 0xFE, f"not a BSAVE-format file (marker byte was {data[0]:02X}h)"
    start = data[1] | (data[2] << 8)
    end = data[3] | (data[4] << 8)
    assert start == 0x0000, f"expected VRAM start 0000h, got {start:04X}h"
    assert end == PAYLOAD_LEN - 1, f"expected VRAM end {PAYLOAD_LEN-1:04X}h, got {end:04X}h"
    payload = data[7:]
    assert len(payload) == PAYLOAD_LEN, f"payload is {len(payload)} bytes, expected {PAYLOAD_LEN}"
    return payload


def rle_encode(data):
    """自前の対称RLE(上記フォーマット参照)。戻り値は
    (compressed_bytes, num_segments)。"""
    out = bytearray()
    segments = 0
    i = 0
    n = len(data)
    while i < n:
        run_len = 1
        while i + run_len < n and data[i + run_len] == data[i] and run_len < 128:
            run_len += 1
        if run_len >= 2:
            out.append(0x80 | (run_len - 1))
            out.append(data[i])
            i += run_len
        else:
            lits = bytearray()
            j = i
            while j < n and len(lits) < 128:
                rl = 1
                while j + rl < n and data[j + rl] == data[j] and rl < 128:
                    rl += 1
                if rl >= 2:
                    break
                lits.append(data[j])
                j += 1
            out.append(len(lits) - 1)
            out.extend(lits)
            i = j
        segments += 1
    return bytes(out), segments


def rle_decode(compressed, num_segments):
    """独立したPythonリファレンスデコーダ(ASM側のロジックと1:1対応、
    回帰テストでの往復検証・Z80実装の突き合わせ用)。"""
    out = bytearray()
    i = 0
    for _ in range(num_segments):
        c = compressed[i]
        i += 1
        length = (c & 0x7F) + 1
        if c & 0x80:
            b = compressed[i]
            i += 1
            out.extend([b] * length)
        else:
            out.extend(compressed[i:i + length])
            i += length
    assert i == len(compressed), "decoder did not consume the whole compressed stream"
    return bytes(out)


def db_bytes(byte_list, per_line=16):
    lines = []
    for i in range(0, len(byte_list), per_line):
        chunk = byte_list[i:i + per_line]
        lines.append("    DB " + ",".join(str(b) for b in chunk))
    return "\n".join(lines)


def emit_asm_tables():
    payload = load_sc2_payload()
    compressed, segments = rle_encode(payload)
    assert rle_decode(compressed, segments) == payload, "RLE round-trip mismatch - encoder bug"
    out = ["; ===== title screen background (SC2, RLE-compressed): generated by "
           "title_bg_gen.py, do not hand-edit ====="]
    out.append(f"TITLE_BG_RLE_SEGMENTS EQU {segments}")
    out.append("TITLE_BG_RLE:")
    out.append(db_bytes(list(compressed)))
    return "\n".join(out)


if __name__ == "__main__":
    payload = load_sc2_payload()
    compressed, segments = rle_encode(payload)
    assert rle_decode(compressed, segments) == payload
    pgt, mid, col = payload[0:0x1800], payload[0x1800:0x2000], payload[0x2000:0x3800]
    pgt_c, _ = rle_encode(pgt)
    mid_c, _ = rle_encode(mid)
    col_c, _ = rle_encode(col)
    print(f"pattern generator : {len(pgt)} -> {len(pgt_c)} bytes ({100*len(pgt_c)/len(pgt):.1f}%)")
    print(f"name/attr/gap     : {len(mid)} -> {len(mid_c)} bytes ({100*len(mid_c)/len(mid):.1f}%)")
    print(f"color table       : {len(col)} -> {len(col_c)} bytes ({100*len(col_c)/len(col):.1f}%)")
    print(f"TOTAL             : {len(payload)} -> {len(compressed)} bytes "
          f"({100*len(compressed)/len(payload):.1f}%, {segments} segments, "
          f"saved {len(payload)-len(compressed)} bytes)")
