"""Generates the placeholder BGM note-period table and pattern data for
Stage2's new Vsync-driven BGM driver (round36-14 follow-up#24: "ではBGMを
実装する...まずStage2から Vsyncを使ってBGMドライバを実装...BGMは空きの
範囲で仮実装").

Channels B/C were explicitly reserved for BGM many rounds ago and never
touched since (see combined_test.asm's own SND_TIMER comment: "PSGは3ch+
ノイズ1chが仕様 2chはBGM用に常に空けておきたいしな") - channel A stays
SFX-only, this file only ever emits data for channels B and C.

PSG tone period formula (real MSX AY-3-8910-compatible chip): the PSG's
own input clock is half the Z80 clock (3579545Hz / 2 = 1789772.5Hz, the
standard, widely-documented MSX constant - independent of and not
previously spelled out anywhere else in this project's own SFX code,
which only ever used a few hand-picked period literals), and
    tone_period = round(clock / (16 * frequency))
12-bit register pair: low byte -> R2/R4 (channel B/C tone period low),
high nibble -> R3/R5 (channel B/C tone period high, top 4 bits must stay
0). This file only ever emits 12-bit-safe periods (all notes below sit
well under 4096), so no masking is needed on the Python side.

Placeholder pattern: a short, simple 2-voice round-and-round melody -
genuinely just a proof that the driver mechanism (Vsync-timed row
advance, independent of MAINLOOP's own free-running frame pace) works,
not real composed music - "空きの範囲で仮実装" per the same instruction.
Channel B carries the melody, channel C a simple one-octave-down echo of
the same line offset by one row (a cheap way to make 2 free channels
sound like slightly more than "one flute playing"). Both channels share
the same per-row duration and the same NOTE_REST sentinel (0xFFh - never
a valid table index, since PERIOD_TABLE has far fewer than 255 entries).
"""
import math

PSG_CLOCK = 3579545 / 2  # 1789772.5Hz - standard MSX AY-3-8910 input clock

# 3 octaves, C3..B5 (36 semitones), equal temperament, A4=440Hz. Index 21
# is A4 - matches the standard note-name list below.
NOTE_NAMES = []
for octave in (3, 4, 5):
    for name in ("C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"):
        NOTE_NAMES.append(f"{name}{octave}")


def note_freq(index):
    # A4 is at index 21 (0-based) in the 24-entry C3..B4 list above.
    semitones_from_a4 = index - 21
    return 440.0 * (2.0 ** (semitones_from_a4 / 12.0))


def tone_period(freq):
    return round(PSG_CLOCK / (16.0 * freq))


PERIOD_TABLE = [tone_period(note_freq(i)) for i in range(len(NOTE_NAMES))]
NOTE_REST = 0xFF

NOTE_INDEX = {name: i for i, name in enumerate(NOTE_NAMES)}


def n(name):
    return NOTE_INDEX[name]


# One row = (note_B, note_C, duration_in_vblank_ticks). duration is how
# many real Vsync ticks (60/sec on real MSX NTSC hardware) this row
# holds before the driver advances to the next one - independent of
# however long MAINLOOP's own current frame happens to take, which is
# the entire point of driving this off H.TIMI instead of a per-frame
# MAINLOOP call (see combined_test.asm's own BGM_TICK comment).
QUARTER = 20   # ~0.33s at 60Hz - brisk enough that a short placeholder loop doesn't drag
HALF = 40

_MELODY = ["C4", "D4", "E4", "G4", "E4", "D4", "C4", "REST",
           "E4", "G4", "A4", "C5", "A4", "G4", "E4", "REST"]


def _melody_row(name, duration):
    note = NOTE_REST if name == "REST" else n(name)
    return (note, duration)


_melody_rows = [_melody_row(name, QUARTER) for name in _MELODY]
# last row of each 8-note phrase held a bit longer (simple phrase-end accent)
_melody_rows[7] = (_melody_rows[7][0], HALF)
_melody_rows[15] = (_melody_rows[15][0], HALF)

# Channel C: the same line, one octave down (-12 semitones), shifted by
# one row (a naive round/canon so both channels are never both resting
# at once) - purely a placeholder-tune trick, not meant to be "real"
# harmony.
_echo_shift = 1
PATTERN_ROWS = []
for i, (note_b, dur) in enumerate(_melody_rows):
    echo_name_idx = (i - _echo_shift) % len(_melody_rows)
    echo_note, _ = _melody_rows[echo_name_idx]
    note_c = NOTE_REST if echo_note == NOTE_REST else echo_note - 12
    PATTERN_ROWS.append((note_b, note_c, dur))

BGM_LOOP_MARK = 0xFE  # sentinel note_B value: "reset to pattern start", not a real row


def db_bytes(byte_list, per_line=16):
    lines = []
    for i in range(0, len(byte_list), per_line):
        chunk = byte_list[i:i + per_line]
        lines.append("    DB " + ",".join(str(b) for b in chunk))
    return "\n".join(lines)


def emit_asm_tables():
    out = ["; ===== BGM note-period table + placeholder pattern: generated by bgm_gen.py, do not hand-edit ====="]
    out.append(f"BGM_NOTE_COUNT EQU {len(PERIOD_TABLE)}")
    out.append(f"BGM_NOTE_REST EQU {NOTE_REST}")
    out.append(f"BGM_LOOP_MARK EQU {BGM_LOOP_MARK}")
    out.append("; low byte (R2/R4), one per note, in NOTE_NAMES order (C3..B4)")
    out.append("BGM_PERIOD_LO:")
    out.append(db_bytes([p & 0xFF for p in PERIOD_TABLE]))
    out.append("; high nibble (R3/R5), one per note")
    out.append("BGM_PERIOD_HI:")
    out.append(db_bytes([(p >> 8) & 0x0F for p in PERIOD_TABLE]))
    out.append("; placeholder pattern rows: note_B, note_C, duration(vblank ticks)")
    out.append("BGM_PATTERN:")
    flat = []
    for note_b, note_c, dur in PATTERN_ROWS:
        flat.extend([note_b, note_c, dur])
    out.append(db_bytes(flat, per_line=15))
    out.append("BGM_PATTERN_LOOP:")
    out.append(f"    DB {BGM_LOOP_MARK}")
    return "\n".join(out)


if __name__ == "__main__":
    print(f"{len(NOTE_NAMES)} notes, periods: {PERIOD_TABLE}")
    print(f"pattern: {len(PATTERN_ROWS)} rows, {len(PATTERN_ROWS) * 3 + 1} bytes total (+{2 * len(PERIOD_TABLE)} bytes period table)")
