"""Converts the 2 BigZum pose sprites (32x32, Sprite Editor JSON) into
MSX hardware sprite pattern data - same 2x2-of-16x16 (TL/TR/BL/BR),
each 16x16 = 4 8x8 sub-patterns (32 bytes), quadrant-splitting/hflip
approach as tools/stage2_tank/tank_gen.py, just with 2 poses instead
of 4 and a fixed base offset (156, right after Zum's own PAT_ZUM_FLIP
at 152-155 - see combined_test.asm's own pattern-code budget comment)
instead of tank_gen.py's always-0 (the tank's patterns are always the
very first ones loaded).

Poses:
  BigZum  - approaching/walking, also used unchanged while airborne
            (no separate jump art was provided - "ジャンプは自機より
            高く32ｐｘ サインジャンプ" describes the ARC, not a new pose)
  BigZumP - punching

Both poses get a mirrored (right-facing) variant, same "反転パターン
はそっちで生成してくれ" precedent as the tank's own poses and Zum's
own single pose - "なので添付のデータは反転も生成": BigZum's own
mirrored pose is actually USED at runtime (unlike Zum's, which enemy_
gen.py generates but combined_test.asm never references) once it
lands behind the tank and turns to face right - see BZ_FACING in
combined_test.asm.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SPRITE_DIR = os.path.join(HERE, "sprites")

POSES = ["BigZum", "BigZumP"]
BASE_OFFSET = 156          # right after PAT_ZUM_FLIP(152-155)
POSE_FLIP_OFFSET = 32      # left-facing PAT_<POSE>_L bases sit here past the 2 right-facing poses (2*16=32)


def load_bits(name):
    return json.load(open(os.path.join(SPRITE_DIR, f"{name}.json")))["bits"]


def hflip_bits(bits):
    return [list(reversed(row)) for row in bits]


def sub8(bits, row0, col0):
    return [row[col0:col0 + 8] for row in bits[row0:row0 + 8]]


def to_bytes(tile8x8):
    out = []
    for row in tile8x8:
        b = 0
        for i, v in enumerate(row):
            if v:
                b |= (0x80 >> i)
        out.append(b)
    return out


def block16_bytes(bits, row0, col0):
    """One 16x16 sprite's 32 bytes: TL8,BL8,TR8,BR8 sub-quadrants."""
    tl = to_bytes(sub8(bits, row0, col0))
    bl = to_bytes(sub8(bits, row0 + 8, col0))
    tr = to_bytes(sub8(bits, row0, col0 + 8))
    br = to_bytes(sub8(bits, row0 + 8, col0 + 8))
    return tl + bl + tr + br


def quadrants_from_bits(bits):
    """Returns [TL(32B), TR(32B), BL(32B), BR(32B)] for one 32x32 bit grid."""
    tl = block16_bytes(bits, 0, 0)
    tr = block16_bytes(bits, 0, 16)
    bl = block16_bytes(bits, 16, 0)
    br = block16_bytes(bits, 16, 16)
    return [tl, tr, bl, br]


def pose_quadrants(name):
    return quadrants_from_bits(load_bits(name))


def pose_quadrants_flipped(name):
    return quadrants_from_bits(hflip_bits(load_bits(name)))


ALL_QUADRANTS = {name: pose_quadrants(name) for name in POSES}
ALL_QUADRANTS_L = {name: pose_quadrants_flipped(name) for name in POSES}


def db_bytes(byte_list, per_line=16):
    lines = []
    for i in range(0, len(byte_list), per_line):
        chunk = byte_list[i:i + per_line]
        lines.append("    DB " + ",".join(f"{b}" for b in chunk))
    return "\n".join(lines)


def _emit_pose_set(out, quadrants_by_name, suffix, base_offset):
    labels = ["TL", "TR", "BL", "BR"]
    for pi, name in enumerate(POSES):
        base = base_offset + pi * 16
        out.append(f"PAT_{name.upper()}{suffix} EQU {base}")
        quads = quadrants_by_name[name]
        for qi, q in enumerate(quads):
            out.append(f"BIGZUM_{name.upper()}{suffix}_{labels[qi]}:")
            out.append(db_bytes(q))


def emit_asm_tables():
    """Each pose gets 4 consecutive pattern-group numbers (TL,TR,BL,BR),
    16 apart per pose (4 quadrants x 4 slots-of-8-bytes each) - right-
    facing poses at BASE_OFFSET..+31, left-facing (mirrored) at
    BASE_OFFSET+POSE_FLIP_OFFSET..+31."""
    out = ["; ===== BigZum sprite patterns: generated by bigzum_gen.py, do not hand-edit ====="]
    out.append(f"BIGZUM_POSE_FLIP_OFFSET EQU {POSE_FLIP_OFFSET}")
    _emit_pose_set(out, ALL_QUADRANTS, "", BASE_OFFSET)
    _emit_pose_set(out, ALL_QUADRANTS_L, "_L", BASE_OFFSET + POSE_FLIP_OFFSET)
    return "\n".join(out)


if __name__ == "__main__":
    for name in POSES:
        print(name, "converted, 4x32 bytes")
    tables_path = os.path.join(HERE, "bigzum_tables.inc.asm")
    with open(tables_path, "w") as f:
        f.write(emit_asm_tables())
    print("wrote", tables_path)
