"""Converts the 2 tank bullet sprites (8x8, Sprite Editor JSON) into a
single BG (background character) pattern each - bullets are drawn as
name-table characters, not hardware sprites, so any number can share a
scanline with the tank/terrain sprites with no "4 sprites per line"
flicker (same reasoning as src/CYBER SHMUP.asm's own player shots).

Each pattern gets loaded into VRAM at TWO different character codes
(see combined_test.asm's BULLETF_SKY_CODE/BULLETF_ROCK_CODE etc.) - one
per background color group - since a name-table character's color is
fixed per 8-code group in SCREEN1, not per screen position. Compositing
onto whichever background is under the bullet's current cell is really
just "use the code whose color group matches that background", not a
per-pixel blend - unlike the terrain's own multi-tone tiles, a bullet
pixel is always solid green with nothing else drawn into the same
8x8 cell.

Poses:
  BulletF - straight-ahead shot
  BulletU - diagonal (up+forward) shot
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SPRITE_DIR = os.path.join(HERE, "sprites")

BULLETS = [("F", "BulletF"), ("U", "BulletU")]


def load_bits(name):
    return json.load(open(os.path.join(SPRITE_DIR, f"{name}.json")))["bits"]


def to_bytes(tile8x8):
    out = []
    for row in tile8x8:
        b = 0
        for i, v in enumerate(row):
            if v:
                b |= (0x80 >> i)
        out.append(b)
    return out


def bullet_pattern(name):
    bits = load_bits(name)
    tile = [row[0:8] for row in bits[0:8]]
    return to_bytes(tile)


ALL_PATTERNS = {code: bullet_pattern(name) for code, name in BULLETS}


def db_bytes(byte_list):
    return "    DB " + ",".join(f"{b}" for b in byte_list)


def emit_asm_tables():
    out = ["; ===== Bullet BG patterns: generated by bullet_gen.py, do not hand-edit ====="]
    for code, name in BULLETS:
        out.append(f"BULLET_{code}_PATTERN:")
        out.append(db_bytes(ALL_PATTERNS[code]))
    return "\n".join(out)


if __name__ == "__main__":
    for code, name in BULLETS:
        print(name, "converted, 8 bytes")
    tables_path = os.path.join(HERE, "bullet_tables.inc.asm")
    with open(tables_path, "w") as f:
        f.write(emit_asm_tables())
    print("wrote", tables_path)
