"""Converts the 2 tank bullet sprites (8x8, Sprite Editor JSON) into
VRAM data for combined_test.asm.

BulletF (straight-ahead) stays a BG (background character) pattern,
drawn as name-table characters rather than a hardware sprite - "水平は
今のままで" (leave the horizontal shot as it is). See combined_test.asm's
BULLETF_SKY_CODE/BULLETF_ROCK_CODE etc: each needs one code per
background color group it can appear over (SCREEN1 color is fixed per
8-code group, not per screen position), so compositing onto whichever
background is under the bullet's current cell is just "use the code
whose color group matches that background", not a per-pixel blend.

BulletU (diagonal, up+forward) is now a hardware sprite instead - "弾は
斜めのみスプライトに変更" - since it no longer needs the sky/rock BG
color-matching dance at all (a hw sprite composites over whatever's
already drawn). The 8x8 source art is embedded into the top-left 8x8
of an otherwise-blank 16x16 canvas (the VDP is already running in
16x16 sprite mode for the tank/enemies, so a new sprite has to be
16x16-shaped too) and converted the same TL/BL/TR/BR quadrant-byte-
order way tank_gen.py/enemy_gen.py already do for their own 16x16
sprites - see block16_bytes there. Kept in the top-left corner (not
centered) so the sprite's own (Y,X) attribute can stay exactly
row*8,col*8, the same anchor point the old BG cell used.

Both poses also get a mirrored (left-facing) version for when the tank
itself is facing/firing left (see combined_test.asm's TANK_FACING) -
same "generate the flip yourself" approach as tank_gen.py's own
POSE_FLIP_OFFSET poses, reusing terrain_gen.py's hflip idea. For
BulletU the source 8x8 bits are mirrored in place and re-embedded at
the same top-left corner (not the whole 16x16 canvas flipped, which
would shift the visible pixels to the top-right and require a
compensating +8 X offset for no visual benefit).
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SPRITE_DIR = os.path.join(HERE, "sprites")


def load_bits(name):
    return json.load(open(os.path.join(SPRITE_DIR, f"{name}.json")))["bits"]


def hflip_bits(bits):
    return [list(reversed(row)) for row in bits]


def to_bytes(tile8x8):
    out = []
    for row in tile8x8:
        b = 0
        for i, v in enumerate(row):
            if v:
                b |= (0x80 >> i)
        out.append(b)
    return out


def bullet_pattern(name, flipped=False):
    bits = load_bits(name)
    if flipped:
        bits = hflip_bits(bits)
    tile = [row[0:8] for row in bits[0:8]]
    return to_bytes(tile)


ALL_F_PATTERNS = {"F": bullet_pattern("BulletF")}
ALL_F_PATTERNS_L = {"F": bullet_pattern("BulletF", flipped=True)}


def bullet_u_sprite(flipped=False):
    """BulletU's 8x8 art, embedded at the top-left of an otherwise-blank
    16x16 sprite canvas: TL8,BL8,TR8,BR8 quadrant byte order (32 bytes),
    same layout as one of tank_gen.py's own 16x16 sprite quadrants."""
    bits = load_bits("BulletU")
    if flipped:
        bits = hflip_bits(bits)
    tile = [row[0:8] for row in bits[0:8]]
    zero8 = [0, 0, 0, 0, 0, 0, 0, 0]
    return to_bytes(tile) + zero8 + zero8 + zero8


BULLET_U_SPRITE = bullet_u_sprite()
BULLET_U_SPRITE_L = bullet_u_sprite(flipped=True)


def db_bytes(byte_list):
    return "    DB " + ",".join(f"{b}" for b in byte_list)


def emit_asm_tables():
    out = ["; ===== Bullet patterns: generated by bullet_gen.py, do not hand-edit ====="]
    out.append("BULLET_F_PATTERN:")
    out.append(db_bytes(ALL_F_PATTERNS["F"]))
    out.append("BULLET_F_L_PATTERN:")
    out.append(db_bytes(ALL_F_PATTERNS_L["F"]))
    out.append("BULLET_U_SPRITE:")
    out.append(db_bytes(BULLET_U_SPRITE))
    out.append("BULLET_U_SPRITE_L:")
    out.append(db_bytes(BULLET_U_SPRITE_L))
    return "\n".join(out)


if __name__ == "__main__":
    print("BulletF converted, 8 bytes (BG pattern)")
    print("BulletU converted, 32 bytes (16x16 hw sprite pattern)")
    tables_path = os.path.join(HERE, "bullet_tables.inc.asm")
    with open(tables_path, "w") as f:
        f.write(emit_asm_tables())
    print("wrote", tables_path)
