"""Converts the ZacoII enemy sprite (16x16, Sprite Editor JSON) into
MSX hardware sprite pattern data - one 16x16 hardware sprite, 4 8x8
sub-patterns in [top-left][bottom-left][top-right][bottom-right] byte
order (32 bytes), same layout as one quadrant of the tank's own 32x32
poses (see tools/stage2_tank/tank_gen.py's block16_bytes).

Also emits a mirrored (left-right flipped) copy for when the enemy
turns back and flies away right-to-left instead of its normal
left-to-right approach - "移動は自機位置をみて手前で引き返す...
引き返す際の左右反転キャラを生成" (watches the player's position and
turns back before reaching them; generate the flipped character for
the turn-back) - same hflip idea as tank_gen.py/bullet_gen.py's own
mirrored poses, generated here rather than needing new source art.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SPRITE_DIR = os.path.join(HERE, "sprites")

ENEMIES = ["ZacoII"]


def load_bits(name):
    return json.load(open(os.path.join(SPRITE_DIR, f"{name}.json")))["bits"]


def hflip_bits(bits):
    return [list(reversed(row)) for row in bits]


def sub8(bits, row0, col0):
    return [row[col0:col0 + 8] for row in bits[row0:row0 + 8]]


def to_bytes(tile8x8):
    out = []
    for row in tile8x8:
        b = 0
        for i, v in enumerate(row):
            if v:
                b |= (0x80 >> i)
        out.append(b)
    return out


def block16_bytes(bits):
    """One 16x16 sprite's 32 bytes: TL8,BL8,TR8,BR8 sub-quadrants."""
    tl = to_bytes(sub8(bits, 0, 0))
    bl = to_bytes(sub8(bits, 8, 0))
    tr = to_bytes(sub8(bits, 0, 8))
    br = to_bytes(sub8(bits, 8, 8))
    return tl + bl + tr + br


ALL_PATTERNS = {name: block16_bytes(load_bits(name)) for name in ENEMIES}
ALL_PATTERNS_FLIP = {name: block16_bytes(hflip_bits(load_bits(name))) for name in ENEMIES}


def db_bytes(byte_list, per_line=16):
    lines = []
    for i in range(0, len(byte_list), per_line):
        chunk = byte_list[i:i + per_line]
        lines.append("    DB " + ",".join(f"{b}" for b in chunk))
    return "\n".join(lines)


def emit_asm_tables():
    out = ["; ===== Enemy sprite patterns: generated by enemy_gen.py, do not hand-edit ====="]
    for name in ENEMIES:
        out.append(f"ENEMY_{name.upper()}:")
        out.append(db_bytes(ALL_PATTERNS[name]))
        out.append(f"ENEMY_{name.upper()}_FLIP:")
        out.append(db_bytes(ALL_PATTERNS_FLIP[name]))
    return "\n".join(out)


if __name__ == "__main__":
    for name in ENEMIES:
        print(name, "converted, 32 bytes + 32 flipped")
    tables_path = os.path.join(HERE, "enemy_tables.inc.asm")
    with open(tables_path, "w") as f:
        f.write(emit_asm_tables())
    print("wrote", tables_path)
