"""Converts Etank (32x32, Sprite Editor JSON) into the BL/BR-quadrant
half of an MSX hardware sprite pattern - same TL/BL/TR/BR sub-8x8
quadrant-split as bigzum_gen.py, but only the bottom half is emitted.

"Etankは戦車で地上用 キャラは32x32のうち左下24x16ドットの範囲" - the art
only occupies the bottom-left of the canvas (confirmed directly: TL and
TR are both fully blank in sprites/Etank.json, and even within the
bottom half cols24-31 are blank too - matching the 24x16 collision
box), so TL/TR are never drawn at runtime (those 2 hw sprite slots are
simply never allocated - see ETANK_SPR_BASE_SLOT in combined_test.asm)
and only BL/BR need real pattern bytes at all.

Originally shared BigZum's own PAT_BIGZUM BL/BR pattern-VRAM groups
dynamically at runtime (the pattern-code budget was tight with
BigZum's own 64 codes loaded). BigZum was removed entirely as a
diagnostic isolation step ("BigZumのコードは全て一旦削除 変わりに
Etankと差し替えてEtank周りが正常動作するか確認する"), freeing up its
whole pattern-code range - Etank now gets its own dedicated PERMANENT
allocation there instead (PAT_ETANK_BL/PAT_ETANK_BR in
combined_test.asm), loaded once at INIT: the 64 bytes this module
emits are LDIRVM'd into VRAM a single time at boot, same convention as
Flyer's own permanent pattern load.

Color is NOT read from the JSON's own fg (8, medium red) - "カラーは
ダークレッド" overrides it to dark red (MSX palette index 6) directly
in combined_test.asm's own ETANK_COLOR constant, not here.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SPRITE_DIR = os.path.join(HERE, "sprites")


def load_bits(name):
    return json.load(open(os.path.join(SPRITE_DIR, f"{name}.json")))["bits"]


def sub8(bits, row0, col0):
    return [row[col0:col0 + 8] for row in bits[row0:row0 + 8]]


def to_bytes(tile8x8):
    out = []
    for row in tile8x8:
        b = 0
        for i, v in enumerate(row):
            if v:
                b |= (0x80 >> i)
        out.append(b)
    return out


def block16_bytes(bits, row0, col0):
    """One 16x16 sprite's 32 bytes: TL8,BL8,TR8,BR8 sub-quadrants -
    same byte ordering as bigzum_gen.py's own block16_bytes."""
    tl = to_bytes(sub8(bits, row0, col0))
    bl = to_bytes(sub8(bits, row0 + 8, col0))
    tr = to_bytes(sub8(bits, row0, col0 + 8))
    br = to_bytes(sub8(bits, row0 + 8, col0 + 8))
    return tl + bl + tr + br


def bottom_quadrants(bits):
    """Returns [BL(32B), BR(32B)] - the bottom half of the 32x32 grid only."""
    bl = block16_bytes(bits, 16, 0)
    br = block16_bytes(bits, 16, 16)
    return [bl, br]


def db_bytes(byte_list, per_line=16):
    lines = []
    for i in range(0, len(byte_list), per_line):
        chunk = byte_list[i:i + per_line]
        lines.append("    DB " + ",".join(f"{b}" for b in chunk))
    return "\n".join(lines)


def emit_asm_tables():
    """ETANK_BL/ETANK_BR: 32 bytes each, contiguous in that order so a
    single 64-byte LDIRVM from ETANK_BL copies both into place at once
    (see ALLOC_ETANK_SLOT)."""
    bits = load_bits("Etank")
    bl, br = bottom_quadrants(bits)
    out = ["; ===== Etank sprite pattern (BL/BR only): generated by etank_gen.py, do not hand-edit ====="]
    out.append("ETANK_BL:")
    out.append(db_bytes(bl))
    out.append("ETANK_BR:")
    out.append(db_bytes(br))
    return "\n".join(out)


if __name__ == "__main__":
    print("Etank converted, 2x32 bytes (BL/BR only)")
    tables_path = os.path.join(HERE, "etank_tables.inc.asm")
    with open(tables_path, "w") as f:
        f.write(emit_asm_tables())
    print("wrote", tables_path)
