"""Converts EtankBullet_8x8.json (Etank's own left-only BG-drawn bullet -
round36-14 follow-up#11: "Etankはスポーン後左へ32px移動したら発射し方向は
左直進のみ 弾はBG使用ファイルEtankBullet") into a single BG pattern-
generator code's own 8 bytes.

Placed at code249 (group31, codes248-255) - the ONLY BG color group this
round's own VRAM survey found with a free (7 of 8 codes unused) pattern
slot AND a background nibble (11, light yellow) matching the source art's
own bg exactly; group31's shared color (0x5Bh = fg5 light blue/bg11 light
yellow, already claimed by SKYSAND_CODE=248's own real content) is left
completely untouched - no new color write, this bullet simply renders in
that same fg5/bg11 (light blue on light yellow) instead of the source
art's own fg8/bg11 (medium red on light yellow), per direct user
confirmation ("では背景色一致は必要なので文字色が近いものを使ってくれ")
after a full 32-group survey found no group whose shared color already
matched fg8/bg11 exactly (every one of BG's 32 groups was already
claimed by *something*, unlike the old "0 spare" belief - see this
round's own HANDOFF entry for the full empirical methodology).
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SPRITE_DIR = os.path.join(HERE, "sprites")


def load_bits(name):
    return json.load(open(os.path.join(SPRITE_DIR, f"{name}.json")))["bits"]


def to_bytes(tile8x8):
    out = []
    for row in tile8x8:
        b = 0
        for i, v in enumerate(row):
            if v:
                b |= (0x80 >> i)
        out.append(b)
    return out


def etank_bullet_pattern():
    bits = load_bits("EtankBullet_8x8")
    tile = [row[0:8] for row in bits[0:8]]
    return to_bytes(tile)


ETANK_BULLET_PATTERN = etank_bullet_pattern()


def db_bytes(byte_list):
    return "    DB " + ",".join(f"{b}" for b in byte_list)


def emit_asm_tables():
    out = ["; ===== EtankBullet BG pattern art: generated by etankbullet_gen.py, do not hand-edit ====="]
    out.append("ETANK_BULLET_PATTERN:")
    out.append(db_bytes(ETANK_BULLET_PATTERN))
    return "\n".join(out)


if __name__ == "__main__":
    print(f"EtankBullet converted: {len(ETANK_BULLET_PATTERN)} bytes (1 BG pattern code)")
