"""Converts FlyerLaser_16x16.json (Flyer's own post-descent horizontal
shot - round36-14 follow-up#12: "その後FlyerLaser発射...自機は狙わず
右方向水平撃ちのみ BG使用") into a single BG pattern-generator code's
own 8 bytes.

The source canvas is nominally 16x16, but every real pixel in it sits
inside rows2-3, cols0-7 - the top-left 8x8 quadrant - so this reuses
EtankBullet's own "just take the top-left 8x8" conversion (same
to_bytes/load_bits shape as etankbullet_gen.py) rather than treating it
as a real 4-quadrant 16x16 sprite; the other 3 quadrants are entirely
blank and simply never referenced.

Placed at code250 (group31, codes248-255 - SKYSAND_CODE=248/
ETANK_BULLET_PATTERN_CODE=249's own group). Chosen over the other
free-but-unmatched BG gaps this round's own VRAM survey found because
Flyer only ever fires this laser right at the very end of its own
diagonal-down-right homing leg (see UOFL_HOME_MOVE's own comment) - the
exact same low-altitude band the Y-8px SandSky-overlap fix in this same
round targets - so the real background behind it is overwhelmingly
likely to be SkySand, not open sky. group31's own shared color (0x5Bh =
fg5 light blue/bg11 light yellow) is therefore reused unchanged, same
"exact bg match, approximate fg" precedent EtankBullet already
established for this identical group (source art wants fg7/bg11 - bg
matches exactly, fg becomes 5 instead of 7).
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SPRITE_DIR = os.path.join(HERE, "sprites")


def load_bits(name):
    return json.load(open(os.path.join(SPRITE_DIR, f"{name}.json")))["bits"]


def to_bytes(tile8x8):
    out = []
    for row in tile8x8:
        b = 0
        for i, v in enumerate(row):
            if v:
                b |= (0x80 >> i)
        out.append(b)
    return out


def flyer_laser_pattern():
    bits = load_bits("FlyerLaser_16x16")
    tile = [row[0:8] for row in bits[0:8]]
    return to_bytes(tile)


FLYER_LASER_PATTERN = flyer_laser_pattern()


def db_bytes(byte_list):
    return "    DB " + ",".join(f"{b}" for b in byte_list)


def emit_asm_tables():
    out = ["; ===== FlyerLaser BG pattern art: generated by flyerlaser_gen.py, do not hand-edit ====="]
    out.append("FLYER_LASER_PATTERN:")
    out.append(db_bytes(FLYER_LASER_PATTERN))
    return "\n".join(out)


if __name__ == "__main__":
    print(f"FlyerLaser converted: {len(FLYER_LASER_PATTERN)} bytes (1 BG pattern code)")
