"""Converts Flyer (32x32, Sprite Editor JSON) into MSX hardware sprite
pattern data - same 2x2-of-16x16 (TL/TR/BL/BR) quadrant-split/hflip
approach as bigzum_gen.py, just 1 pose instead of 2 (Flyer has no
separate punch/alternate-pose art, only ever the one sprite) and a
fixed base offset of 220 (right after BigZum's own last group at 219 -
see combined_test.asm's own pattern-code budget comment).

Flyer gets its own PERMANENT pattern allocation (no dynamic VRAM
sharing with anything - unlike a since-reverted, since-not-yet-
reimplemented Etank, nothing currently competes for pattern-code
budget). Both facings are generated (needed for real: Flyer cruises
left, then reverses and homes back right/down toward the tank -
"反転して自機に向かって降りてくる" - same "反転も生成" precedent as
every other multi-directional enemy here).
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SPRITE_DIR = os.path.join(HERE, "sprites")

BASE_OFFSET = 220         # right after BigZum's own last group (156-219)
POSE_FLIP_OFFSET = 16     # left-facing PAT_FLYER_L base sits 16 past the right-facing one (4 quadrants x4 slots-of-8-bytes)


def load_bits(name):
    return json.load(open(os.path.join(SPRITE_DIR, f"{name}.json")))["bits"]


def hflip_bits(bits):
    return [list(reversed(row)) for row in bits]


def sub8(bits, row0, col0):
    return [row[col0:col0 + 8] for row in bits[row0:row0 + 8]]


def to_bytes(tile8x8):
    out = []
    for row in tile8x8:
        b = 0
        for i, v in enumerate(row):
            if v:
                b |= (0x80 >> i)
        out.append(b)
    return out


def block16_bytes(bits, row0, col0):
    tl = to_bytes(sub8(bits, row0, col0))
    bl = to_bytes(sub8(bits, row0 + 8, col0))
    tr = to_bytes(sub8(bits, row0, col0 + 8))
    br = to_bytes(sub8(bits, row0 + 8, col0 + 8))
    return tl + bl + tr + br


def quadrants_from_bits(bits):
    tl = block16_bytes(bits, 0, 0)
    tr = block16_bytes(bits, 0, 16)
    bl = block16_bytes(bits, 16, 0)
    br = block16_bytes(bits, 16, 16)
    return [tl, tr, bl, br]


def db_bytes(byte_list, per_line=16):
    lines = []
    for i in range(0, len(byte_list), per_line):
        chunk = byte_list[i:i + per_line]
        lines.append("    DB " + ",".join(f"{b}" for b in chunk))
    return "\n".join(lines)


def emit_asm_tables():
    bits = load_bits("Flyer")
    quads = quadrants_from_bits(bits)
    quads_l = quadrants_from_bits(hflip_bits(bits))
    labels = ["TL", "TR", "BL", "BR"]
    out = ["; ===== Flyer sprite patterns: generated by flyer_gen.py, do not hand-edit ====="]
    out.append(f"PAT_FLYER EQU {BASE_OFFSET}")
    for qi, q in enumerate(quads):
        out.append(f"FLYER_{labels[qi]}:")
        out.append(db_bytes(q))
    out.append(f"PAT_FLYER_L EQU {BASE_OFFSET + POSE_FLIP_OFFSET}")
    for qi, q in enumerate(quads_l):
        out.append(f"FLYER_L_{labels[qi]}:")
        out.append(db_bytes(q))
    return "\n".join(out)


if __name__ == "__main__":
    print("Flyer converted, 4x32 bytes x2 facings")
    tables_path = os.path.join(HERE, "flyer_tables.inc.asm")
    with open(tables_path, "w") as f:
        f.write(emit_asm_tables())
    print("wrote", tables_path)
