"""Converts FlyerLaser_16x16.json (Flyer's own post-descent horizontal
shot - round36-14 follow-up#12: "その後FlyerLaser発射...自機は狙わず
右方向水平撃ちのみ BG使用") into a single BG pattern-generator code's
own 8 bytes.

The source canvas is nominally 16x16, but every real pixel in it sits
inside rows2-3, cols0-7 - the top-left 8x8 quadrant - so this reuses
EtankBullet's own "just take the top-left 8x8" conversion (same
to_bytes/load_bits shape as etankbullet_gen.py) rather than treating it
as a real 4-quadrant 16x16 sprite; the other 3 quadrants are entirely
blank and simply never referenced.

Placed at code221 (group27, codes216-223 - THUNDER_CODE_BASE=216-219/
THUNDERS_CODE=220's own group, Thunder's boss-attack art). Two earlier
homes, both corrected by real-hardware feedback:
1. code250 (group31, bg11) - guessed the background would be SandSky
   (Flyer fires this right at the end of its own diagonal-down-right
   homing leg, the same low-altitude band the paired Y-8px fix
   targets) - wrong, the real background is open sky (bg5).
2. code139 (group17, bg5 - NIGHT_CODE/Mine's own group) - bg matched
   exactly, but a full 32-group survey found no group anywhere
   combining fg7(cyan, the source art's own fg)+bg5, so the beam
   rendered fg1(black) - "流石にブラックはレーザーに見えない".
Landed on group27 instead: fg7 is an EXACT match here (Thunder's own
color, 0x71h), so the beam itself finally renders true cyan, at the
cost of bg1(black) - a dark box against open sky instead of an
invisible one. Chose "looks like a laser, imperfect background" over
"perfect background, doesn't look like a laser" per the more specific,
repeated ask ("レーザー自体はシアン"). Repainting group17 or group27
themselves was ruled out both times - either would also recolor an
already-shipped, already-tuned feature sharing that same group (Mine/
NIGHT_CODE for group17, Thunder's own boss-attack visual for group27).
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SPRITE_DIR = os.path.join(HERE, "sprites")


def load_bits(name):
    return json.load(open(os.path.join(SPRITE_DIR, f"{name}.json")))["bits"]


def to_bytes(tile8x8):
    out = []
    for row in tile8x8:
        b = 0
        for i, v in enumerate(row):
            if v:
                b |= (0x80 >> i)
        out.append(b)
    return out


def flyer_laser_pattern():
    bits = load_bits("FlyerLaser_16x16")
    tile = [row[0:8] for row in bits[0:8]]
    return to_bytes(tile)


FLYER_LASER_PATTERN = flyer_laser_pattern()


def db_bytes(byte_list):
    return "    DB " + ",".join(f"{b}" for b in byte_list)


def emit_asm_tables():
    out = ["; ===== FlyerLaser BG pattern art: generated by flyerlaser_gen.py, do not hand-edit ====="]
    out.append("FLYER_LASER_PATTERN:")
    out.append(db_bytes(FLYER_LASER_PATTERN))
    return "\n".join(out)


if __name__ == "__main__":
    print(f"FlyerLaser converted: {len(FLYER_LASER_PATTERN)} bytes (1 BG pattern code)")
