"""Converts FlyerLaser_16x16.json (Flyer's own post-descent horizontal
shot - round36-14 follow-up#12: "その後FlyerLaser発射...自機は狙わず
右方向水平撃ちのみ BG使用") into a single BG pattern-generator code's
own 8 bytes.

The source canvas is nominally 16x16, but every real pixel in it sits
inside rows2-3, cols0-7 - the top-left 8x8 quadrant - so this reuses
EtankBullet's own "just take the top-left 8x8" conversion (same
to_bytes/load_bits shape as etankbullet_gen.py) rather than treating it
as a real 4-quadrant 16x16 sprite; the other 3 quadrants are entirely
blank and simply never referenced.

Placed at code139 (group17, codes136-143 - NIGHT_CODE=136/MINE1_CODE=
137/MINE2_CODE=138's own group). First shipped at code250 (group31,
reasoning: Flyer only ever fires this laser at the very end of its own
diagonal-down-right homing leg, the same low-altitude SandSky band the
paired Y-8px fix targets, so group31's bg11 seemed like the right
match) - real-hardware feedback ("FlyerLaserのBG背景色がイエローに
なってる 背景と同じくライトブルーだぞ") showed that guess was wrong:
the actual background behind it is open sky (bg5 light blue), not
SandSky. group17's own shared color (0x15h = fg1 black/bg5 light blue)
is an EXACT match on bg; a full 32-group survey found no group anywhere
combining fg7(cyan, the source art's own fg)+bg5, so fg renders as 1
(black) instead - same "exact bg match, approximate fg" precedent
EtankBullet's own group31 reuse already established, just unable to
land as close on the fg axis this time (repainting group17 itself was
ruled out - it would also recolor Mine and NIGHT_CODE's own already-
tuned night palette, both sharing this same group).
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SPRITE_DIR = os.path.join(HERE, "sprites")


def load_bits(name):
    return json.load(open(os.path.join(SPRITE_DIR, f"{name}.json")))["bits"]


def to_bytes(tile8x8):
    out = []
    for row in tile8x8:
        b = 0
        for i, v in enumerate(row):
            if v:
                b |= (0x80 >> i)
        out.append(b)
    return out


def flyer_laser_pattern():
    bits = load_bits("FlyerLaser_16x16")
    tile = [row[0:8] for row in bits[0:8]]
    return to_bytes(tile)


FLYER_LASER_PATTERN = flyer_laser_pattern()


def db_bytes(byte_list):
    return "    DB " + ",".join(f"{b}" for b in byte_list)


def emit_asm_tables():
    out = ["; ===== FlyerLaser BG pattern art: generated by flyerlaser_gen.py, do not hand-edit ====="]
    out.append("FLYER_LASER_PATTERN:")
    out.append(db_bytes(FLYER_LASER_PATTERN))
    return "\n".join(out)


if __name__ == "__main__":
    print(f"FlyerLaser converted: {len(FLYER_LASER_PATTERN)} bytes (1 BG pattern code)")
