"""Converts the 5 homing-missile facing sprites (8x8, Sprite Editor
JSON) into BG (name-table) pattern data - a hw sprite was NOT an
option here: the sprite pattern-code budget (0-255) is already at
0-251 used (tank/ZacoII/BulletU/Zum/BigZum/Flyer), leaving only 4 free
slots, nowhere near the 20 a 5-facing hw sprite would need (16x16-
padded, 4 codes/facing, same "VDP is already in 16x16 mode" constraint
bullet_gen.py's own BulletU already documents). BG pattern codes are a
separate, mostly-free 0-255 space, and the missile is small/coarse
enough (already discretized to 5 possible directions, no sub-pixel
movement) that column/row-granular BG movement - the same approach
BulletF (and BulletU during the boss fight) already use - fits
naturally, and avoids the same per-scanline hw-sprite-priority
disappearing-bullet class of bug that already forced BulletU to BG
during the boss fight in the first place.

SL=facing left, DL=facing down-left, Down=facing down, DR=facing
down-right, SR=facing right - "180度を5段階45度ごと" (180 degrees in 5
steps of 45 degrees, SL at -90 through SR at +90, pivoting on Down).
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SPRITE_DIR = os.path.join(HERE, "sprites")

FACINGS = ["SL", "DL", "Down", "DR", "SR"]


def load_bits(name):
    return json.load(open(os.path.join(SPRITE_DIR, f"Horming{name}_8x8.json")))["bits"]


def to_bytes(tile8x8):
    out = []
    for row in tile8x8:
        b = 0
        for i, v in enumerate(row):
            if v:
                b |= (0x80 >> i)
        out.append(b)
    return out


ALL_PATTERNS = {name: to_bytes(load_bits(name)) for name in FACINGS}


def db_bytes(byte_list):
    return "    DB " + ",".join(f"{b}" for b in byte_list)


def emit_asm_tables():
    out = ["; ===== Homing missile BG patterns: generated by horming_gen.py, do not hand-edit ====="]
    for name in FACINGS:
        out.append(f"HORMING_{name.upper()}_PATTERN:")
        out.append(db_bytes(ALL_PATTERNS[name]))
    return "\n".join(out)


if __name__ == "__main__":
    print(f"Horming missile: {len(FACINGS)} 8x8 BG patterns converted")
