"""Converts the 5 homing-missile facing sprites (8x8, Sprite Editor
JSON) into MSX hardware sprite pattern data.

Round 1 of this feature used BG (name-table) drawing instead of a hw
sprite, reasoning the sprite pattern-code budget was nearly exhausted
(only 4 free slots). Corrected: "スプライトパターンそんなに使ってる
か? 自機とボスだけだぞ もしそうなら動的に書き換えしてくれ...BGでは
...動きがガタガタで速すぎるんだよ スプライト必須" - once the boss is
active, ZacoII/Zum/Flyer never spawn again (same "オールフリー"
principle the boss's own body already relies on for BigZum's block),
so their entire pattern-code footprint is genuinely free for dynamic
reuse - this reuses Flyer's own whole block (see combined_test.asm's
own PAT_HORMING_SL comment). BG's own column-granular movement was too
choppy for a fast homing missile - a real hw sprite moves in real
pixels instead.

Each 8x8 source image is embedded into the top-left of an otherwise-
blank 16x16 sprite canvas (the VDP is already in 16x16 sprite mode for
the tank/enemies/BulletU, so a new sprite has to be 16x16-shaped too),
same TL/BL/TR/BR quadrant-byte-order convention as bullet_gen.py's own
bullet_u_sprite() - not centered, so each sprite's own (Y,X) attribute
can stay exactly the missile's own real top-left pixel position, no
compensating offset needed.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SPRITE_DIR = os.path.join(HERE, "sprites")

FACINGS = ["SL", "DL", "Down", "DR", "SR"]


def load_bits(name):
    return json.load(open(os.path.join(SPRITE_DIR, f"Horming{name}_8x8.json")))["bits"]


def to_bytes(tile8x8):
    out = []
    for row in tile8x8:
        b = 0
        for i, v in enumerate(row):
            if v:
                b |= (0x80 >> i)
        out.append(b)
    return out


def horming_sprite(name):
    bits = load_bits(name)
    tile = [row[0:8] for row in bits[0:8]]
    zero8 = [0, 0, 0, 0, 0, 0, 0, 0]
    return to_bytes(tile) + zero8 + zero8 + zero8


ALL_SPRITES = {name: horming_sprite(name) for name in FACINGS}


def horming_bg_pattern(name):
    """Flat, unpadded 8-byte BG (name-table) version of the same source
    art the hw sprite pool uses - round36-12 ("弾数を増やす...BGも合わ
    せて使用する 4発追加"): the extra 4 instances are BG-cell-drawn
    (see combined_test.asm's own HORMING_BG_POOL comment for why - both
    the hw sprite pattern-number budget and the sprite ATTRIBUTE slot
    budget were confirmed fully exhausted during the boss fight). Same
    8x8 source bits as horming_sprite() above, just not padded into a
    16x16 sprite canvas - a BG tile is inherently 8x8 already."""
    bits = load_bits(name)
    tile = [row[0:8] for row in bits[0:8]]
    return to_bytes(tile)


ALL_BG_PATTERNS = {name: horming_bg_pattern(name) for name in FACINGS}


def db_bytes(byte_list):
    return "    DB " + ",".join(f"{b}" for b in byte_list)


def emit_asm_tables():
    out = ["; ===== Homing missile hw sprite patterns: generated by horming_gen.py, do not hand-edit ====="]
    for name in FACINGS:
        out.append(f"HORMING_{name.upper()}_SPRITE:")
        out.append(db_bytes(ALL_SPRITES[name]))
    for name in FACINGS:
        out.append(f"HORMING_BG_{name.upper()}_PATTERN:")
        out.append(db_bytes(ALL_BG_PATTERNS[name]))
    return "\n".join(out)


if __name__ == "__main__":
    print(f"Horming missile: {len(FACINGS)} 16x16-padded hw sprite patterns converted")
    print(f"Horming missile: {len(FACINGS)} flat 8x8 BG patterns converted (round36-12)")
