"""Converts Mine1_8x8.json/Mine2_8x8.json (Flyer's own dropped landmine,
2-frame animation - round36-14 follow-up#12: "スポーンから32px左に移動
したら 添付データのMineを放物線で投下...Mine1と2のアニメで") into 2 BG
pattern-generator codes' own 8 bytes each.

Placed at codes137-138 (group17, codes136-143 - NIGHT_CODE=136's own
group). Full VRAM-budget survey (this round, same symbol-table cross-
reference + real-emulator-boot-color-table methodology round36-14
follow-up#11 established) found group17 has 7 of its 8 codes genuinely
pattern-free, AND its own shared color (0x15h = fg1 black/bg5 light
blue) is an EXACT match to both source images' own fg1/bg5 - no new
color write needed at all, same "reuse an already-colored group
unchanged" idiom as EtankBullet's own group31 reuse (that case only
matched on bg; this one is a full match on both channels, pure luck).

Mine itself renders as a hw sprite for now (per direct user framing,
"取り敢えずスプライトだがBGに変更するかも" - tentative, may switch to
BG later), NOT via these BG codes - this module exists only because
the same "no free codes" 16x16-sprite-pattern-space finding that forced
EtankBullet onto BG earlier this session (full symbol-table audit,
sprite-space codes0-255 verified 100% claimed with zero safe temporal-
reuse candidate remaining - unlike EBullet's own SBEAM_CODE reuse, every
boss-exclusive range is already double- or triple-claimed) forced Mine
onto BG too, despite the user's own sprite framing - flagged back to the
user alongside the pre-ship render, per this session's own established
"render before shipping" workflow.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SPRITE_DIR = os.path.join(HERE, "sprites")


def load_bits(name):
    return json.load(open(os.path.join(SPRITE_DIR, f"{name}.json")))["bits"]


def to_bytes(tile8x8):
    out = []
    for row in tile8x8:
        b = 0
        for i, v in enumerate(row):
            if v:
                b |= (0x80 >> i)
        out.append(b)
    return out


def mine_pattern(name):
    bits = load_bits(name)
    tile = [row[0:8] for row in bits[0:8]]
    return to_bytes(tile)


MINE1_PATTERN = mine_pattern("Mine1_8x8")
MINE2_PATTERN = mine_pattern("Mine2_8x8")


def db_bytes(byte_list):
    return "    DB " + ",".join(f"{b}" for b in byte_list)


def emit_asm_tables():
    out = ["; ===== Mine BG pattern art: generated by mine_gen.py, do not hand-edit ====="]
    out.append("MINE1_PATTERN:")
    out.append(db_bytes(MINE1_PATTERN))
    out.append("MINE2_PATTERN:")
    out.append(db_bytes(MINE2_PATTERN))
    return "\n".join(out)


if __name__ == "__main__":
    print(f"Mine converted: {len(MINE1_PATTERN)}+{len(MINE2_PATTERN)} bytes (2 BG pattern codes)")
