"""Converts Sasapi (the boss, 64x64, Sprite Editor JSON) into MSX
hardware sprite pattern data - same TL/BL/TR/BR-per-16x16-quadrant
approach as bigzum_gen.py/flyer_gen.py, just a 4x4 grid of 16x16
quadrants (16 of them) instead of a 2x2 one, since 64x64 is 4x the
linear size of the 32x32 sprites everything else here uses.

Unlike BigZum/Flyer, Sasapi does NOT get its own permanent pattern-code
allocation - "自機以外はもうスポーンしないんで オールフリー": by the
time the boss can spawn (BOSS_SPAWN_TICK=999), every ordinary enemy
type has been refusing to spawn for 49 GAME_TICKs already
(ENEMY_SPAWN_STOP_TICK=950 - see SPAWN_STOPPED), so their own pattern-
VRAM is free to reuse. Sasapi's 16 quadrants x4 patterns = exactly 64
slots, exactly BigZum's own whole footprint (PAT_BIGZUM..+63, all 4 of
its pose/facing groups) - reused wholesale rather than carving out a
5th permanent block this file doesn't have room for (see
combined_test.asm's own pattern-code budget comment: Flyer's own last
group already ends at 251, only 4 slots free above it). Loaded into
VRAM fresh at boss-spawn time (once - the boss never despawns, so this
only ever runs once per game), same "copy at spawn instead of at INIT"
idiom etank_gen.py's own comment describes for Etank/BigZum sharing.

Only 1 facing is generated (no left/right mirrored art) - the boss
only ever moves horizontally and nothing in the given spec asked for a
flipped look on direction change, unlike Flyer's own explicit "反転も
生成してくれ". Revisit if a screenshot/complaint says otherwise.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SPRITE_DIR = os.path.join(HERE, "sprites")

GRID = 4   # 4x4 quadrants of 16x16 = 64x64


def load_bits(name):
    return json.load(open(os.path.join(SPRITE_DIR, f"{name}.json")))["bits"]


def sub8(bits, row0, col0):
    return [row[col0:col0 + 8] for row in bits[row0:row0 + 8]]


def to_bytes(tile8x8):
    out = []
    for row in tile8x8:
        b = 0
        for i, v in enumerate(row):
            if v:
                b |= (0x80 >> i)
        out.append(b)
    return out


def block16_bytes(bits, row0, col0):
    """One 16x16 sprite's 32 bytes: TL8,BL8,TR8,BR8 sub-quadrants - same
    real-hardware pattern-group byte order as bigzum_gen.py/
    flyer_gen.py's own block16_bytes."""
    tl = to_bytes(sub8(bits, row0, col0))
    bl = to_bytes(sub8(bits, row0 + 8, col0))
    tr = to_bytes(sub8(bits, row0, col0 + 8))
    br = to_bytes(sub8(bits, row0 + 8, col0 + 8))
    return tl + bl + tr + br


def quadrants_from_bits(bits):
    """Row-major 4x4 walk (TL of the whole 64x64 first, then rightward,
    then down a row) - BOSS_QUAD_OFFSETS in combined_test.asm walks the
    same order to pair each quadrant's pattern group with its own
    on-screen Y/X delta."""
    quads = []
    for row0 in range(0, 64, 16):
        for col0 in range(0, 64, 16):
            quads.append(block16_bytes(bits, row0, col0))
    return quads


def db_bytes(byte_list, per_line=16):
    lines = []
    for i in range(0, len(byte_list), per_line):
        chunk = byte_list[i:i + per_line]
        lines.append("    DB " + ",".join(f"{b}" for b in chunk))
    return "\n".join(lines)


def emit_asm_tables():
    """16 quadrants x 32 bytes (TL,BL,TR,BR sub-patterns) = 512 bytes,
    laid out contiguously in on-screen quadrant order under one label -
    combined_test.asm loads the whole block with a single 512-byte
    LDIRVM into PAT_BIGZUM*8 (reused - see this module's own docstring)
    rather than 16 separate calls, since both source and destination are
    already contiguous. No EQU base emitted here since the destination
    is decided in combined_test.asm, not by this file."""
    bits = load_bits("Sasapi")
    quads = quadrants_from_bits(bits)
    out = ["; ===== Sasapi (boss) sprite patterns: generated by sasapi_gen.py, do not hand-edit ====="]
    out.append("SASAPI_QUADS:")
    for q in quads:
        out.append(db_bytes(q))
    return "\n".join(out)


if __name__ == "__main__":
    print("Sasapi converted, 16x32 bytes (1 facing)")
    tables_path = os.path.join(HERE, "sasapi_tables.inc.asm")
    with open(tables_path, "w") as f:
        f.write(emit_asm_tables())
    print("wrote", tables_path)
