"""Converts SasapiHand_64x64.json (the boss's attack-pose art, drawn
straight into SCREEN1's own name table while parked at the right edge,
NOT a hw sprite - "右端に戻ったら添付のパターンをBGに描画しスプライト
は一旦消す") into 64 row-major 8x8 BG pattern tiles (8 rows x 8 cols of
8x8 pixels each) - the exact order the name table itself is laid out
in, NOT the TL/BL/TR/BR sprite-quadrant order sasapi_gen.py/tank_gen.py
use for hw sprites, since this never becomes a hw sprite.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SPRITE_DIR = os.path.join(HERE, "sprites")


def load_bits(name):
    return json.load(open(os.path.join(SPRITE_DIR, f"{name}.json")))["bits"]


def to_bytes(tile8x8):
    out = []
    for row in tile8x8:
        b = 0
        for i, v in enumerate(row):
            if v:
                b |= (0x80 >> i)
        out.append(b)
    return out


def tiles_row_major(bits):
    tiles = []
    for ty in range(8):
        for tx in range(8):
            tile = [row[tx * 8:tx * 8 + 8] for row in bits[ty * 8:ty * 8 + 8]]
            tiles.append(to_bytes(tile))
    return tiles


SASAPI_HAND_TILES = tiles_row_major(load_bits("SasapiHand_64x64"))


def db_bytes(byte_list):
    return "    DB " + ",".join(f"{b}" for b in byte_list)


def emit_asm_tables():
    out = ["; ===== Sasapi attack-pose BG art: generated by sasapi_hand_gen.py, do not hand-edit ====="]
    out.append("SASAPI_HAND_TILES:")
    for tile in SASAPI_HAND_TILES:
        out.append(db_bytes(tile))
    return "\n".join(out)


if __name__ == "__main__":
    print(f"SasapiHand converted: {len(SASAPI_HAND_TILES)} 8x8 BG tiles ({len(SASAPI_HAND_TILES) * 8} bytes)")
