"""Converts SBeam_8x8.json (the boss's "サンダービーム" attack - a real
hw sprite, unlike Thunder's own BG-drawn bolt) into a 16x16 hw sprite
pattern: the 8x8 source art embedded at the top-left of an otherwise-
blank 16x16 canvas (TL8,BL8,TR8,BR8 quadrant byte order), same shape as
bullet_gen.py's own bullet_u_sprite() - the VDP is already running in
16x16 sprite mode for the tank/enemies/boss, so a new sprite has to be
16x16-shaped too, even though only its own top-left 8x8 is ever lit.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SPRITE_DIR = os.path.join(HERE, "sprites")


def load_bits(name):
    return json.load(open(os.path.join(SPRITE_DIR, f"{name}.json")))["bits"]


def to_bytes(tile8x8):
    out = []
    for row in tile8x8:
        b = 0
        for i, v in enumerate(row):
            if v:
                b |= (0x80 >> i)
        out.append(b)
    return out


def sbeam_sprite():
    bits = load_bits("SBeam_8x8")
    tile = [row[0:8] for row in bits[0:8]]
    zero8 = [0, 0, 0, 0, 0, 0, 0, 0]
    return to_bytes(tile) + zero8 + zero8 + zero8


SBEAM_SPRITE = sbeam_sprite()


def db_bytes(byte_list):
    return "    DB " + ",".join(f"{b}" for b in byte_list)


def emit_asm_tables():
    out = ["; ===== SBeam hw sprite art: generated by sbeam_gen.py, do not hand-edit ====="]
    out.append("SBEAM_SPRITE:")
    out.append(db_bytes(SBEAM_SPRITE))
    return "\n".join(out)


if __name__ == "__main__":
    print(f"SBeam converted: {len(SBEAM_SPRITE)} bytes (16x16 hw sprite pattern)")
