"""Converts Thunder_16x16.json (the boss's "サンダー" attack - a
lightning-bolt column drawn straight into the name table while the boss
patrols between poses, NOT a hw sprite - "BGで描画") into 4 row-major
8x8 BG pattern tiles (2 rows x2 cols of 8x8 pixels each) - the exact
name-table layout order (TL,TR,BL,BR), NOT the sprite TL/BL/TR/BR
quadrant order tank_gen.py/sasapi_gen.py use for hw sprites, since this
never becomes a hw sprite. Same conversion shape as sasapi_hand_gen.py's
own tiles_row_major, just a 2x2 grid instead of 8x8 (this image is
16x16, not 64x64).
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SPRITE_DIR = os.path.join(HERE, "sprites")


def load_bits(name):
    return json.load(open(os.path.join(SPRITE_DIR, f"{name}.json")))["bits"]


def to_bytes(tile8x8):
    out = []
    for row in tile8x8:
        b = 0
        for i, v in enumerate(row):
            if v:
                b |= (0x80 >> i)
        out.append(b)
    return out


def tiles_row_major(bits):
    tiles = []
    for ty in range(2):
        for tx in range(2):
            tile = [row[tx * 8:tx * 8 + 8] for row in bits[ty * 8:ty * 8 + 8]]
            tiles.append(to_bytes(tile))
    return tiles


THUNDER_TILES = tiles_row_major(load_bits("Thunder_16x16"))

# "やっぱThunderSは2セル分でいいわ サンダーが着地したら左右同時に2セル
# 描いて消せばおｋ 地形に沿うのは無しで" - ThunderS is NOT a moving hw
# sprite (round9 dropped that idea) - just 1 more static 8x8 BG tile,
# same conversion shape as the single-tile bullet_gen.py patterns, drawn
# once at the landing point (1 cell left, 1 cell right of the bolt) when
# the bolt reaches the terrain, and erased again once the bolt itself
# finishes shrinking.
THUNDERS_TILE = to_bytes([row[0:8] for row in load_bits("ThunderS_8x8")[0:8]])


def db_bytes(byte_list):
    return "    DB " + ",".join(f"{b}" for b in byte_list)


def emit_asm_tables():
    out = ["; ===== Thunder BG art: generated by thunder_gen.py, do not hand-edit ====="]
    out.append("THUNDER_TILES:")
    for tile in THUNDER_TILES:
        out.append(db_bytes(tile))
    out.append("THUNDERS_TILE:")
    out.append(db_bytes(THUNDERS_TILE))
    return "\n".join(out)


if __name__ == "__main__":
    print(f"Thunder converted: {len(THUNDER_TILES)} 8x8 BG tiles ({len(THUNDER_TILES) * 8} bytes)")
    print(f"ThunderS converted: 1 8x8 BG tile ({len(THUNDERS_TILE)} bytes)")
